title: Luke Grippa
baeurl: /

destination: docs/

google_analytics: "G-5N8HSMWXXH"

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
